//Generated by https://m3.material.io/theme-builder#/custom

package io.github.dosukoijuku.octopusenergychecker.android.view.theme
import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFFFA9FA)
val md_theme_dark_onPrimary = Color(0xFF5A005F)
val md_theme_dark_primaryContainer = Color(0xFF7F0087)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD6F8)
val md_theme_dark_secondary = Color(0xFFC5C0FF)
val md_theme_dark_onSecondary = Color(0xFF2400A2)
val md_theme_dark_secondaryContainer = Color(0xFF3700E1)
val md_theme_dark_onSecondaryContainer = Color(0xFFE3DFFF)
val md_theme_dark_tertiary = Color(0xFFC7BFFF)
val md_theme_dark_onTertiary = Color(0xFF2D1B83)
val md_theme_dark_tertiaryContainer = Color(0xFF45369B)
val md_theme_dark_onTertiaryContainer = Color(0xFFE5DEFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF24005A)
val md_theme_dark_onBackground = Color(0xFFEADDFF)
val md_theme_dark_surface = Color(0xFF24005A)
val md_theme_dark_onSurface = Color(0xFFEADDFF)
val md_theme_dark_surfaceVariant = Color(0xFF4E444B)
val md_theme_dark_onSurfaceVariant = Color(0xFFD1C3CC)
val md_theme_dark_outline = Color(0xFF998D96)
val md_theme_dark_inverseOnSurface = Color(0xFF24005A)
val md_theme_dark_inverseSurface = Color(0xFFEADDFF)
val md_theme_dark_inversePrimary = Color(0xFFA600B0)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFA9FA)
val md_theme_dark_outlineVariant = Color(0xFF4E444B)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFF050F7)
